functionsDirectory = "D:\\PROJECTS\\Solo Travel Safety\\Code\\Solo Travel Safety\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []

[build]
publish = "D:\\PROJECTS\\Solo Travel Safety\\Code\\Solo Travel Safety\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "D:\\PROJECTS\\Solo Travel Safety\\Code\\Solo Travel Safety\\netlify\\functions"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
command = "npm run dev"
port = 5173.0
publish = "dist"

[functions]

[functions."*"]

[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.supabase.co https://www.youtube.com https://*.youtube.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://*.perplexity.ai data:; img-src 'self' data: https: blob: https://*.ytimg.com https://i.ytimg.com https://*.youtube.com; connect-src 'self' https://*.supabase.co https://api.netlify.com https://*.sentry.io https://www.youtube.com https://*.youtube.com https://www.youtube-nocookie.com; media-src 'self' https://www.youtube.com https://*.youtube.com https://www.youtube-nocookie.com blob:; frame-src 'self' https://www.youtube.com https://youtube.com https://www.youtube-nocookie.com https://*.youtube.com; child-src 'self' https://www.youtube.com https://youtube.com https://www.youtube-nocookie.com https://*.youtube.com; worker-src 'self' blob: https://*.youtube.com; frame-ancestors 'self'; base-uri 'self'; form-action 'self'; upgrade-insecure-requests"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=(self \"https://www.youtube.com\" \"https://www.youtube-nocookie.com\" \"https://*.youtube.com\"), accelerometer=(self \"https://www.youtube.com\" \"https://www.youtube-nocookie.com\" \"https://*.youtube.com\")"
X-XSS-Protection = "1; mode=block"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
Cross-Origin-Opener-Policy = "same-origin-allow-popups"

[[headers]]
for = "/api/*"

[headers.values]
Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' https://*.supabase.co; frame-ancestors 'none'"

[[headers]]
for = "/netlify/functions/*"

[headers.values]
Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' https://*.supabase.co; frame-ancestors 'none'"

[[headers]]
for = "/auth/callback"

[headers.values]
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://*.supabase.co; style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src 'self' data:; connect-src 'self' https://*.supabase.co; frame-ancestors 'none'"
Cache-Control = "public, max-age=31536000, immutable, public, max-age=31536000, immutable, public, max-age=31536000, immutable, public, max-age=31536000, immutable, public, max-age=31536000, immutable, public, max-age=31536000, immutable, public, max-age=31536000, immutable, public, max-age=31536000, immutable, public, max-age=31536000, immutable, public, max-age=31536000, immutable, public, max-age=31536000, immutable, public, max-age=31536000, immutable, no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]